### ISSUE TITLE
Error exporting wooden boat asset

### ISSUE THREAD

**Issue by mahagyak** [Makopolo/megascan_houdini20.0_USD_plugin#1]
When I try to export[ this wooden boat asset ](https://quixel.com/megascans/home?category=3D+asset&search=wooden&search=boat&assetId=vemgdcmbw) from bridge, I get the following error in the houdini console, and the import fails:

```
Traceback (most recent call last):
  File "C:\Users/Mate/Documents/Megascans_Library/support/plugins/houdini/4.6/MSLiveLink/scripts/python\MSPlugin\MSImporter.py", line 40, in importController
    import3d.importAsset(assetData, importOptions, importParams)
  File "C:\Users/Mate/Documents/Megascans_Library/support/plugins/houdini/4.6/MSLiveLink/scripts/python\MSPlugin\AssetImporters\Import3D.py", line 504, in importAsset
    ImportUSD().importNormalUSD(assetData, importOptions, importParams)
  File "C:\Users/Mate/Documents/Megascans_Library/support/plugins/houdini/4.6/MSLiveLink/scripts/python\MSPlugin\AssetImporters\Import3D.py", line 33, in importNormalUSD
    self.usdAssetSetup(importedAssets, assetData, importOptions, importParams)       
  File "C:\Users/Mate/Documents/Megascans_Library/support/plugins/houdini/4.6/MSLiveLink/scripts/python\MSPlugin\AssetImporters\Import3D.py", line 353, in usdAssetSetup
    newVariName = rchop(importedAssets[0].name(),"0")
TypeError: 'NoneType' object is not subscriptable
```

I can export other assets without issue.

Env:
Houdini 20.0.724 Python 3.9, Windows, Karma materials

**Comment by Makopolo** [comment]
I have updated a few things. 
It seems to work on my end. can error out when some of the script isn't installed properly.
rchop() is a function I have added in Utilities/AtlasSplitter.py so if it's not installed properly it can error out.
Try copy and pasting all the files again to make sure.

If there's any other issue be sure to comment again
